// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WordClock

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_onbutton(lv_event_t * e);
lv_obj_t * ui_onbutton;
lv_obj_t * ui_onbuttonlabel;
void ui_event_offbutton(lv_event_t * e);
lv_obj_t * ui_offbutton;
lv_obj_t * ui_offbuttonlable;
void ui_event_configbutton(lv_event_t * e);
lv_obj_t * ui_configbutton;
lv_obj_t * ui_configlabel;
void ui_event_settingbutton(lv_event_t * e);
lv_obj_t * ui_settingbutton;
lv_obj_t * ui_settinglabel;

// SCREEN: ui_configscreen
void ui_configscreen_screen_init(void);
lv_obj_t * ui_configscreen;
lv_obj_t * ui_updatetimepanel;
lv_obj_t * ui_updatetimepanel2;
lv_obj_t * ui_redslider;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label10;
lv_obj_t * ui_redslider1;
lv_obj_t * ui_redslider2;

// SCREEN: ui_settingscreen
void ui_settingscreen_screen_init(void);
lv_obj_t * ui_settingscreen;
lv_obj_t * ui_sendstatisticlabel;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Slider2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_onbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_onbutton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_offbutton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_configbutton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_settingbutton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_offbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_onbutton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_offbutton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_configbutton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_settingbutton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_configbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_configscreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_configscreen_screen_init);
    }
}
void ui_event_settingbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingscreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_settingscreen_screen_init);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_configscreen_screen_init();
    ui_settingscreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
