// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WordClock

#ifndef _WORDCLOCK_UI_H
#define _WORDCLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_onbutton(lv_event_t * e);
extern lv_obj_t * ui_onbutton;
extern lv_obj_t * ui_onbuttonlabel;
void ui_event_offbutton(lv_event_t * e);
extern lv_obj_t * ui_offbutton;
extern lv_obj_t * ui_offbuttonlable;
void ui_event_configbutton(lv_event_t * e);
extern lv_obj_t * ui_configbutton;
extern lv_obj_t * ui_configlabel;
void ui_event_settingbutton(lv_event_t * e);
extern lv_obj_t * ui_settingbutton;
extern lv_obj_t * ui_settinglabel;
// SCREEN: ui_configscreen
void ui_configscreen_screen_init(void);
extern lv_obj_t * ui_configscreen;
extern lv_obj_t * ui_updatetimepanel;
extern lv_obj_t * ui_updatetimepanel2;
extern lv_obj_t * ui_redslider;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_redslider1;
extern lv_obj_t * ui_redslider2;
// SCREEN: ui_settingscreen
void ui_settingscreen_screen_init(void);
extern lv_obj_t * ui_settingscreen;
extern lv_obj_t * ui_sendstatisticlabel;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
