// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WordClock

#include "../ui.h"

void ui_comp_updatetimepanel_create_hook(lv_obj_t * comp)
{
}
