// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WordClock

#ifndef _UI_COMP_UPDATETIMEPANEL_H
#define _UI_COMP_UPDATETIMEPANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT updatetimepanel
#define UI_COMP_UPDATETIMEPANEL_UPDATETIMEPANEL 0
#define UI_COMP_UPDATETIMEPANEL_UPDATETIMESWITCH 1
#define UI_COMP_UPDATETIMEPANEL_LABEL7 2
#define _UI_COMP_UPDATETIMEPANEL_NUM 3
lv_obj_t * ui_updatetimepanel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
