// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WordClock

#include "../ui.h"

void ui_configscreen_screen_init(void)
{
    ui_configscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_configscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_width(ui_configscreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_configscreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_updatetimepanel = ui_updatetimepanel_create(ui_configscreen);
    lv_obj_set_x(ui_updatetimepanel, 1);
    lv_obj_set_y(ui_updatetimepanel, -118);

    ui_updatetimepanel2 = ui_updatetimepanel_create(ui_configscreen);
    lv_obj_set_x(ui_updatetimepanel2, 1);
    lv_obj_set_y(ui_updatetimepanel2, -58);

    lv_label_set_text(ui_comp_get_child(ui_updatetimepanel2, UI_COMP_UPDATETIMEPANEL_LABEL7), "Use night light");

    ui_redslider = lv_slider_create(ui_configscreen);
    lv_slider_set_value(ui_redslider, 70, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_redslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_redslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_redslider, 246);
    lv_obj_set_height(ui_redslider, 10);
    lv_obj_set_x(ui_redslider, -50);
    lv_obj_set_y(ui_redslider, 7);
    lv_obj_set_align(ui_redslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_redslider, lv_color_hex(0xBBB6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_redslider, lv_color_hex(0xF2111C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_redslider, lv_color_hex(0x8D8C8C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_configscreen);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 35);
    lv_obj_set_x(ui_Button5, 0);
    lv_obj_set_y(ui_Button5, 130);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x929090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 2);
    lv_obj_set_y(ui_Label8, -1);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Back");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xF6F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_configscreen);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -154);
    lv_obj_set_y(ui_Label10, -18);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "RGB Slider");

    ui_redslider1 = lv_slider_create(ui_configscreen);
    lv_slider_set_value(ui_redslider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_redslider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_redslider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_redslider1, 246);
    lv_obj_set_height(ui_redslider1, 10);
    lv_obj_set_x(ui_redslider1, -48);
    lv_obj_set_y(ui_redslider1, 41);
    lv_obj_set_align(ui_redslider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_redslider1, lv_color_hex(0xBBB6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_redslider1, lv_color_hex(0x11CC11), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_redslider1, lv_color_hex(0x8D8C8C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_redslider2 = lv_slider_create(ui_configscreen);
    lv_slider_set_value(ui_redslider2, 80, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_redslider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_redslider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_redslider2, 246);
    lv_obj_set_height(ui_redslider2, 10);
    lv_obj_set_x(ui_redslider2, -49);
    lv_obj_set_y(ui_redslider2, 78);
    lv_obj_set_align(ui_redslider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_redslider2, lv_color_hex(0xBBB6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_redslider2, lv_color_hex(0x2111F2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_redslider2, lv_color_hex(0x8D8C8C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}
