// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WordClock

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onbutton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_onbutton, 100);
    lv_obj_set_height(ui_onbutton, 50);
    lv_obj_set_x(ui_onbutton, -70);
    lv_obj_set_y(ui_onbutton, -70);
    lv_obj_set_align(ui_onbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_onbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_onbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_onbutton, lv_color_hex(0x23D139), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_onbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_onbuttonlabel = lv_label_create(ui_onbutton);
    lv_obj_set_width(ui_onbuttonlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_onbuttonlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_onbuttonlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_onbuttonlabel, "ON");

    ui_offbutton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_offbutton, 100);
    lv_obj_set_height(ui_offbutton, 50);
    lv_obj_set_x(ui_offbutton, 60);
    lv_obj_set_y(ui_offbutton, -70);
    lv_obj_set_align(ui_offbutton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_offbutton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_offbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_offbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_offbutton, lv_color_hex(0xD31E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offbuttonlable = lv_label_create(ui_offbutton);
    lv_obj_set_width(ui_offbuttonlable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offbuttonlable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_offbuttonlable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_offbuttonlable, "OFF");

    ui_configbutton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_configbutton, 115);
    lv_obj_set_height(ui_configbutton, 50);
    lv_obj_set_x(ui_configbutton, 0);
    lv_obj_set_y(ui_configbutton, 3);
    lv_obj_set_align(ui_configbutton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_configbutton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_configbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_configbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_configbutton, lv_color_hex(0x9F9C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_configbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configlabel = lv_label_create(ui_configbutton);
    lv_obj_set_width(ui_configlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_configlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_configlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_configlabel, "Configure");
    lv_obj_set_style_text_color(ui_configlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_configlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingbutton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_settingbutton, 115);
    lv_obj_set_height(ui_settingbutton, 50);
    lv_obj_set_x(ui_settingbutton, 0);
    lv_obj_set_y(ui_settingbutton, 70);
    lv_obj_set_align(ui_settingbutton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_settingbutton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_settingbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingbutton, lv_color_hex(0x9F9C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settinglabel = lv_label_create(ui_settingbutton);
    lv_obj_set_width(ui_settinglabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settinglabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settinglabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settinglabel, "Setting");
    lv_obj_set_style_text_color(ui_settinglabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settinglabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_onbutton, ui_event_onbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_offbutton, ui_event_offbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configbutton, ui_event_configbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingbutton, ui_event_settingbutton, LV_EVENT_ALL, NULL);

}
