// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WordClock

#include "../ui.h"

void ui_settingscreen_screen_init(void)
{
    ui_settingscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sendstatisticlabel = ui_updatetimepanel_create(ui_settingscreen);
    lv_obj_set_x(ui_sendstatisticlabel, 0);
    lv_obj_set_y(ui_sendstatisticlabel, -107);

    lv_label_set_text(ui_comp_get_child(ui_sendstatisticlabel, UI_COMP_UPDATETIMEPANEL_LABEL7), "Share Usage Statistics");

    ui_Button6 = lv_btn_create(ui_settingscreen);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 35);
    lv_obj_set_x(ui_Button6, 0);
    lv_obj_set_y(ui_Button6, 130);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x929090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Back");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xF6F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_settingscreen);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}
